version: '3'

services:
  mantis: &mantis
    container_name: mantistable_web
    image: cremarco/mantistable_py:latest
    command: bash -c "python manage.py collectstatic --noinput &&
                      python manage.py makemigrations &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:80"
    ports:
      - "80:80"
    links:
      - mongo
    depends_on:
      - redis
      - mongo
      - celery_worker
    environment:
      - REDIS_URI=redis://mantistable_redis_1:6379
      - DEBUG_MODE=False
      - SECRET_KEY=pg*z8ugm&zms=v9cl28_ya4$$*n00&0t4cp^j49scb70-kyh@vy
  mongo:
    container_name: mantistable_mongo
    image: mongo
    command: mongod --port 27021
    ports:
     - '27021:27021'
    volumes:
      - data:/data/db
  redis:
    container_name: mantistable_redis
    image: redis
    ports:
      - "6381:6381"
  celery_worker: &celery
    container_name: mantistable_celery_worker
    <<: *mantis
    command: celery -A app worker --loglevel=info --autoscale=100,4 -Qcelery
    ports: []
    depends_on:
      - redis
      - mongo
 
volumes:
  data:
